<?php

namespace Tests\Feature;

use Bouncer;
use Tests\TestCase;
use Silber\Bouncer\Database\Role;
use Illuminate\Foundation\Testing\RefreshDatabase;

class InstallSystemTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        \Route::middleware('install.system')->any('_test/route', function () {
            return 'OK';
        });
    }

    /** @test */
    function it_show_form_to_install_the_system()
    {
        $this->withoutExceptionHandling()
            ->get('/_test/route')
            ->assertStatus(302);
    }

    /** @test */
    function it_install_database_and_redirect_to_form_create_admin()
    {
        $this->get('install/system')
            ->assertStatus(302)
            ->assertRedirect('install/admin');

        $this->assertTrue(Role::all()->isNotEmpty());
    }

    /** @test */
    function it_create_admin_user()
    {
        $this->post('install/admin', [
            'name' => 'Cristian',
            'email' => 'example@example.com',
            'password' => '123456',
            'password_confirmation' => '123456'
        ])
            ->assertStatus(302)
            ->assertRedirect('home');

        $this->assertCredentials([
            'name' => 'cristian',
            'email' => 'example@example.com',
            'password' => '123456'
        ]);
    }
}
